package ru.be_more.orange_forum.bus

sealed class Event

object BackPressed : Event()
object AppToBeClosed : Event()
object DownloadedThreadEntered : Event()
object UndownloadedThreadEntered : Event()
object FavoriteThreadEntered : Event()
object UnfavoriteThreadEntered : Event()
object FavoriteBoardEntered : Event()
object UnfavoriteBoardEntered : Event()
object ThreadEntered : Event()
object BoardEntered : Event()
object RefreshFavorite: Event()
object RefreshDownload: Event()
object VideoToBeClosed: Event()
object BoardToBeOpened: Event()
object BoardToBeClosed: Event()
object ThreadToBeOpened: Event()
object ThreadToBeClosed: Event()
object AddToFavorite: Event()
object FavoriteAdded: Event()
object AddToDownload: Event()
object Downloaded: Event()
object RemoveFromFavorite: Event()
object FavoriteRemoved: Event()
object RemoveFromDownload: Event()
object DownloadRemoved: Event()