package ru.be_more.orange_forum.consts


const val CAT_TAG = "CAT_FRAGMENT"
const val BOARD_TAG = "BOARD_FRAGMENT"
const val THREAD_TAG = "THREAD_FRAGMENT"
const val FAVORITE_TAG = "FAVORITE_FRAGMENT"
const val DOWNLOAD_TAG = "DOWNLOAD_FRAGMENT"
const val PREF_TAG = "PREF_FRAGMENT"
const val POST_IN_BOARD_TAG = "POST_IN_BOARD_FRAGMENT"
const val POST_IN_THREAD_TAG = "POST_IN_THREAD_FRAGMENT"
const val POST_TAG = "POST_FRAGMENT"